### ISSUE TITLE
Some confussion...

### ISSUE THREAD

**Issue by tio-trom** [leapcode/bitmask-vpn#4]
Hi. I am deeply confused. Is this Bitmask VPN client or Riseup VPN client?

**Comment by micah** [comment]
On 2021-08-13 08:25:47, Tio wrote:
> Hi. I am deeply confused. Is this Bitmask VPN client or Riseup VPN client?

The Bitmask client is a 'white-label' client that can be used for any
compatible provider. The RiseupVPN client is a 'branded' version of the
Bitmask VPN client, with graphics and pre-configured options.
